name: Auto-add issues to project
on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/studio-prime/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}
